export const COMMENTS = [
  {
    id: 0,
    campsiteId: 0,
    rating: 5,
    text: "Equally ethereal and glamorous, the Goddess gown features a soft ball gown silhouette complemented by a figure-defining, dropped, basque waistline",
    author: "Simon Hunt",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 1,
    campsiteId: 0,
    rating: 3,
    text: "Effortlessly chic and romantic.",
    author: "Zandra Katherine",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 2,
    campsiteId: 0,
    rating: 4,
    text: "This intricately embellished fit-and-flare gown is the epitome of effortless yet sophisticated glamour.",
    author: "Amy Keophilavong",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 3,
    campsiteId: 0,
    rating: 3,
    text: "This simple and chic yet unexpected ball gown is crafted with Cartago satin.",
    author: "Jean Luc",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 4,
    campsiteId: 0,
    rating: 5,
    text: "Chic and sophisticated, this dramatically-draped fit-and-flare gown is the epitome of timeless elegance.",
    author: "R. E. Osariemen",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 5,
    campsiteId: 1,
    rating: 4,
    text: "Chic and sophisticated, this dramatically-draped fit-and-flare gown is the epitome of timeless elegance.",
    author: "Juan Cortez",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 6,
    campsiteId: 1,
    rating: 5,
    text: "This chic and sophisticated dress.",
    author: "McKenzie Sebastian",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 7,
    campsiteId: 1,
    rating: 5,
    text: "Beautiful and chic yet unexpected ball gown is crafted with Cartago satin",
    author: "Brennen Ech",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 8,
    campsiteId: 1,
    rating: 4,
    text: "Best of all, its full, tiered skirt creates a whimsical, cloud-like effect that is bound to have you floating down the aisle.",
    author: "Amy Keophilavong",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 9,
    campsiteId: 1,
    rating: 5,
    text: "Georgeous dress. It's all I ever wanted!",
    author: "Jordan Runn",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 10,
    campsiteId: 2,
    rating: 5,
    text: "Equally romantic and unique, this exquisite strapless ball gown.",
    author: "Olaf the Snowman",
    date: "2019-02-18T18:12Z",
  },
  {
    id: 11,
    campsiteId: 2,
    rating: 1,
    text: "We had to leave about 2am to go back to the city because the quiet was just too much!",
    author: "Vincent and Mona Lisa Gambini",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 12,
    campsiteId: 2,
    rating: 5,
    text: "Georgeous dress. It's all I ever wanted!",
    author: "Ann Dabramov",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 13,
    campsiteId: 2,
    rating: 4,
    text: "This dreamy corseted fit-and-flare gown is crafted with layers of silk tulle accompanied by a delicate layer of intricately beaded lace.",
    author: "Amy Keophilavong",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 14,
    campsiteId: 2,
    rating: 5,
    text: "Elegant dress. It's all I ever wanted!",
    author: "Dave Lister",
    date: "2019-08-04T20:11Z",
  },
  {
    id: 15,
    campsiteId: 5,
    rating: 4,
    text: "Dreamy and elegant.",
    author: "Markell Richards",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 16,
    campsiteId: 3,
    rating: 5,
    text: "The exquisite craftsmanship of the ruched bodice continues into an ethereal A-line skirt adorned with bold silver embroidery.",
    author: "Amy Keophilavong",
    date: "2018-07-23T19:44Z",
  },
  {
    id: 17,
    campsiteId: 3,
    rating: 5,
    text: "What a magnificent dress!",
    author: "Tinus Lorvaldes",
    date: "2018-10-25T16:30Z",
  },
  {
    id: 18,
    campsiteId: 3,
    rating: 4,
    text: "Equally sweet and sophisticated dress!",
    author: "Chloe Haskins",
    date: "2017-06-17T03:33Z",
  },
  {
    id: 19,
    campsiteId: 5,
    rating: 5,
    text: "I love the shoes.",
    author: "Minae Lee",
    date: "2019-02-18T18:12Z",
  },
];
